
package com.panthera.student_ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentsPort", targetNamespace = "http://www.panthera.com/student-ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentsPort {


    /**
     * 
     * @param deleteStudentRequest
     * @return
     *     returns com.panthera.student_ws.DeleteStudentResponse
     */
    @WebMethod
    @WebResult(name = "deleteStudentResponse", targetNamespace = "http://www.panthera.com/student-ws", partName = "deleteStudentResponse")
    public DeleteStudentResponse deleteStudent(
        @WebParam(name = "deleteStudentRequest", targetNamespace = "http://www.panthera.com/student-ws", partName = "deleteStudentRequest")
        DeleteStudentRequest deleteStudentRequest);

    /**
     * 
     * @param getAllStudentRequest
     * @return
     *     returns com.panthera.student_ws.GetAllStudentResponse
     */
    @WebMethod
    @WebResult(name = "getAllStudentResponse", targetNamespace = "http://www.panthera.com/student-ws", partName = "getAllStudentResponse")
    public GetAllStudentResponse getAllStudent(
        @WebParam(name = "getAllStudentRequest", targetNamespace = "http://www.panthera.com/student-ws", partName = "getAllStudentRequest")
        GetAllStudentRequest getAllStudentRequest);

    /**
     * 
     * @param updateStudentRequest
     * @return
     *     returns com.panthera.student_ws.UpdateStudentResponse
     */
    @WebMethod
    @WebResult(name = "updateStudentResponse", targetNamespace = "http://www.panthera.com/student-ws", partName = "updateStudentResponse")
    public UpdateStudentResponse updateStudent(
        @WebParam(name = "updateStudentRequest", targetNamespace = "http://www.panthera.com/student-ws", partName = "updateStudentRequest")
        UpdateStudentRequest updateStudentRequest);

    /**
     * 
     * @param getStudentByIdRequest
     * @return
     *     returns com.panthera.student_ws.GetStudentByIdResponse
     */
    @WebMethod
    @WebResult(name = "getStudentByIdResponse", targetNamespace = "http://www.panthera.com/student-ws", partName = "getStudentByIdResponse")
    public GetStudentByIdResponse getStudentById(
        @WebParam(name = "getStudentByIdRequest", targetNamespace = "http://www.panthera.com/student-ws", partName = "getStudentByIdRequest")
        GetStudentByIdRequest getStudentByIdRequest);

    /**
     * 
     * @param addStudentRequest
     * @return
     *     returns com.panthera.student_ws.AddStudentResponse
     */
    @WebMethod
    @WebResult(name = "addStudentResponse", targetNamespace = "http://www.panthera.com/student-ws", partName = "addStudentResponse")
    public AddStudentResponse addStudent(
        @WebParam(name = "addStudentRequest", targetNamespace = "http://www.panthera.com/student-ws", partName = "addStudentRequest")
        AddStudentRequest addStudentRequest);

}
